"""Constants for the Controlel Home Assistant integration."""

from controlel.application.configuration.canonical_defaults import (
    NEW_CONFIGURATION_DEBUG_DURATION_SECONDS,
    NEW_CONFIGURATION_DEBUG_UNTIL_CHANGED,
    NEW_CONFIGURATION_DIAGNOSTIC_STEADY_PROFILE,
    NEW_CONFIGURATION_HEAT_DELIVERY_ASSIST_TARGET_CELSIUS,
    NEW_CONFIGURATION_HEAT_DEMAND_CONFIRMATION_SECONDS,
    NEW_CONFIGURATION_HEATING_TURN_OFF_DIFFERENTIAL_CELSIUS,
    NEW_CONFIGURATION_HEATING_TURN_ON_DIFFERENTIAL_CELSIUS,
    NEW_CONFIGURATION_INDETERMINATE_GRACE_PERIOD_SECONDS,
    NEW_CONFIGURATION_MAXIMUM_FUTURE_SKEW_SECONDS,
    NEW_CONFIGURATION_MINIMUM_HEATING_OFF_SECONDS,
    NEW_CONFIGURATION_MINIMUM_HEATING_ON_SECONDS,
    NEW_CONFIGURATION_PRIMARY_MEASUREMENT_MAX_AGE_SECONDS,
    NEW_CONFIGURATION_TARGET_TEMPERATURE_CELSIUS,
)
from controlel.domain import notifications as core_notifications

DOMAIN = "controlel"
INTEGRATION_VERSION = "0.14.0"
CONFIG_ENTRY_VERSION = 1

CONTROL_MODE_SIMPLE = "simple_switch"
CONTROL_MODE_CUSTOM = "custom_services"

CONF_SENSOR_ID = "sensor_id"
CONF_SENSOR_NAME = "sensor_name"
CONF_TEMPERATURE_ENTITY_ID = "temperature_entity_id"
CONF_ZONE_ID = "zone_id"
CONF_ZONE_NAME = "zone_name"
CONF_TARGET_TEMPERATURE = "target_temperature"
CONF_HEATING_TURN_ON_DIFFERENTIAL = "heating_turn_on_differential"
CONF_HEATING_TURN_OFF_DIFFERENTIAL = "heating_turn_off_differential"
CONF_HEAT_DEMAND_CONFIRMATION_DURATION_MINUTES = "heat_demand_confirmation_duration_minutes"
CONF_HEAT_DEMAND_CONFIRMATION_DURATION = "heat_demand_confirmation_duration"
CONF_MINIMUM_HEATING_ON_TIME_MINUTES = "minimum_heating_on_time_minutes"
CONF_MINIMUM_HEATING_ON_TIME = "minimum_heating_on_time"
CONF_MINIMUM_HEATING_OFF_TIME_MINUTES = "minimum_heating_off_time_minutes"
CONF_MINIMUM_HEATING_OFF_TIME = "minimum_heating_off_time"
CONF_DIAGNOSTIC_PROFILE = "diagnostic_profile"
CONF_DEBUG_DURATION_MINUTES = "debug_duration_minutes"
CONF_DEBUG_DURATION = "debug_duration"
CONF_DEBUG_UNTIL_CHANGED = "debug_until_changed"
CONF_DIAGNOSTIC_PROFILE_BEFORE_DEBUG = "diagnostic_profile_before_debug"
CONF_HEAT_SOURCE_CONTROL_MODE = "heat_source_control_mode"
CONF_CONTROLLED_ENTITY_ID = "controlled_entity_id"
CONF_SHOW_ADVANCED = "show_advanced"
CONF_PRIMARY_MEASUREMENT_MAX_AGE_MINUTES = "primary_measurement_max_age_minutes"
CONF_PRIMARY_MEASUREMENT_MAX_AGE = "primary_measurement_max_age"
CONF_MAX_FUTURE_SKEW = "max_future_skew"
CONF_INDETERMINATE_GRACE_PERIOD_MINUTES = "indeterminate_grace_period_minutes"
CONF_INDETERMINATE_GRACE_PERIOD = "indeterminate_grace_period"
CONF_INDETERMINATE_TIMEOUT_ACTION = "indeterminate_timeout_action"
CONF_ENABLE_SERVICE_DOMAIN = "enable_service_domain"
CONF_ENABLE_SERVICE_NAME = "enable_service_name"
CONF_ENABLE_TARGET_ENTITY_ID = "enable_target_entity_id"
CONF_DISABLE_SERVICE_DOMAIN = "disable_service_domain"
CONF_DISABLE_SERVICE_NAME = "disable_service_name"
CONF_DISABLE_TARGET_ENTITY_ID = "disable_target_entity_id"
CONF_HEAT_DELIVERY_MODE = "heat_delivery_mode"
CONF_HEAT_DELIVERY_ACTUATOR_ENTITY_ID = "heat_delivery_actuator_entity_id"
CONF_HEAT_DELIVERY_OWNERSHIP = "heat_delivery_ownership"
CONF_HEAT_DELIVERY_ASSIST_POLICY = "heat_delivery_assist_policy"
CONF_HEAT_DELIVERY_ASSIST_TARGET = "heat_delivery_assist_target"
CONF_NOTIFICATIONS = "notifications"

NOTIFICATION_TRANSPORT_HOME_ASSISTANT = "home_assistant_notify"
DEFAULT_NOTIFICATION_MAXIMUM_PER_WINDOW = core_notifications.DEFAULT_NOTIFICATION_MAXIMUM_PER_WINDOW
DEFAULT_NOTIFICATION_RATE_WINDOW_SECONDS = core_notifications.DEFAULT_NOTIFICATION_RATE_WINDOW.total_seconds()
DEFAULT_CRITICAL_NOTIFICATION_MAXIMUM_PER_WINDOW = core_notifications.DEFAULT_CRITICAL_MAXIMUM_PER_WINDOW
DEFAULT_CRITICAL_NOTIFICATION_RATE_WINDOW_SECONDS = core_notifications.DEFAULT_CRITICAL_RATE_WINDOW.total_seconds()
DEFAULT_NOTIFICATION_HISTORY_CAPACITY = core_notifications.DEFAULT_NOTIFICATION_HISTORY_CAPACITY

HEAT_DELIVERY_MODE_UNMANAGED = "unmanaged"
HEAT_DELIVERY_MODE_SETPOINT_ASSIST = "setpoint_assist"
HEAT_DELIVERY_OWNERSHIP_DEVICE = "device_owned"
HEAT_DELIVERY_OWNERSHIP_CONTROLEL = "controlel_owned"
HEAT_DELIVERY_ASSIST_NONE = "no_assist"
HEAT_DELIVERY_ASSIST_ALWAYS = "always_assist_while_heating"
DEFAULT_HEAT_DELIVERY_ASSIST_TARGET = NEW_CONFIGURATION_HEAT_DELIVERY_ASSIST_TARGET_CELSIUS

DEFAULT_TARGET_TEMPERATURE = NEW_CONFIGURATION_TARGET_TEMPERATURE_CELSIUS
DEFAULT_HEATING_TURN_ON_DIFFERENTIAL = NEW_CONFIGURATION_HEATING_TURN_ON_DIFFERENTIAL_CELSIUS
DEFAULT_HEATING_TURN_OFF_DIFFERENTIAL = NEW_CONFIGURATION_HEATING_TURN_OFF_DIFFERENTIAL_CELSIUS
DEFAULT_HEAT_DEMAND_CONFIRMATION_DURATION = NEW_CONFIGURATION_HEAT_DEMAND_CONFIRMATION_SECONDS
LEGACY_HEAT_DEMAND_CONFIRMATION_DURATION = 0.0
MAX_HEAT_DEMAND_CONFIRMATION_DURATION = 86400.0
DEFAULT_MINIMUM_HEATING_ON_TIME = NEW_CONFIGURATION_MINIMUM_HEATING_ON_SECONDS
DEFAULT_MINIMUM_HEATING_OFF_TIME = NEW_CONFIGURATION_MINIMUM_HEATING_OFF_SECONDS
DEFAULT_DIAGNOSTIC_PROFILE = NEW_CONFIGURATION_DIAGNOSTIC_STEADY_PROFILE
LEGACY_DIAGNOSTIC_PROFILE = "detailed"
DEFAULT_DEBUG_DURATION = NEW_CONFIGURATION_DEBUG_DURATION_SECONDS
DEFAULT_DEBUG_UNTIL_CHANGED = NEW_CONFIGURATION_DEBUG_UNTIL_CHANGED
DEFAULT_DIAGNOSTIC_PROFILE_BEFORE_DEBUG = "detailed"
DIAGNOSTIC_PROFILE_BASIC = "basic"
DIAGNOSTIC_PROFILE_DETAILED = "detailed"
DIAGNOSTIC_PROFILE_DEBUG = "debug"
LEGACY_HEATING_TURN_ON_DIFFERENTIAL = 0.0
LEGACY_HEATING_TURN_OFF_DIFFERENTIAL = 0.0
LEGACY_MINIMUM_HEATING_ON_TIME = 0.0
LEGACY_MINIMUM_HEATING_OFF_TIME = 0.0
DEFAULT_PRIMARY_MEASUREMENT_MAX_AGE = NEW_CONFIGURATION_PRIMARY_MEASUREMENT_MAX_AGE_SECONDS
DEFAULT_MAX_FUTURE_SKEW = NEW_CONFIGURATION_MAXIMUM_FUTURE_SKEW_SECONDS
DEFAULT_INDETERMINATE_GRACE_PERIOD = NEW_CONFIGURATION_INDETERMINATE_GRACE_PERIOD_SECONDS
DEFAULT_INDETERMINATE_TIMEOUT_ACTION = "disable_heating"

ATTR_UNIT_OF_MEASUREMENT = "unit_of_measurement"
ATTR_DEVICE_CLASS = "device_class"
STATE_UNKNOWN = "unknown"
STATE_UNAVAILABLE = "unavailable"
UNIT_CELSIUS = "°C"
UNIT_FAHRENHEIT = "°F"

RECOVERABLE_SERVICE_ISSUE_SUFFIX = "heat_source_service_failure"
FATAL_RUNTIME_ISSUE_SUFFIX = "fatal_runtime_failure"
