"""Application configuration resolution."""

from controlel.application.configuration.canonical_v3 import (
    CANONICAL_CONFIGURATION_SCHEMA_VERSION_V3,
    CanonicalConfigurationRevisionV3,
    CanonicalFieldMetadataV3,
    ConfigurationDefaultPolicyV3,
    ConfigurationEditabilityV3,
    ConfigurationOwnerV3,
    DiagnosticDebugPolicyV3,
    DiagnosticsConfigurationV3,
    HeatingConfigurationV3,
    HeatingGlobalConfigurationV3,
    HeatSourceCommandStrategyV3,
    HeatSourceConfigurationV3,
    HeatSourceObservationBindingsV3,
    HeatSourceProtectionPolicyV3,
    NotificationRecipientConfigurationV3,
    NotificationsConfigurationV3,
    PrimaryTemperatureSensorV3,
    ProviderServiceCallV3,
    ZoneConfigurationV3,
    ZoneDemandPolicyV3,
    ZoneHeatDeliveryConfigurationV3,
    ZoneTopologyV3,
    canonical_field_registry_v3,
)
from controlel.application.configuration.canonical_v3_authoring import (
    GREENFIELD_HEAT_SOURCE_ID_V3,
    GREENFIELD_PRIMARY_SENSOR_ID_V3,
    GREENFIELD_ZONE_ID_V3,
    GreenfieldHeatingBindingsV3,
    author_greenfield_heating_scopes_v3,
    conversion_configuration_id_v3,
    new_configuration_id_v3,
)
from controlel.application.configuration.canonical_v3_conversion import (
    CanonicalConfigurationConversionReviewV3,
)
from controlel.application.configuration.canonical_v3_lifecycle import (
    ActiveCanonicalConfigurationV3,
    CanonicalConfigurationDraftV3,
    CanonicalConfigurationLifecycleV3,
    CanonicalConfigurationValidationV3,
    CanonicalReferenceBindingV3,
    CanonicalReferenceHealthV3,
    ConfigurationScopesV3,
    canonical_reference_bindings_v3,
)
from controlel.application.configuration.canonical_v3_migration import (
    CanonicalV2ToV3MigrationError,
    migrate_heating_v2_revision_to_v3,
)

__all__ = [
    "CANONICAL_CONFIGURATION_SCHEMA_VERSION_V3",
    "ActiveCanonicalConfigurationV3",
    "CanonicalConfigurationDraftV3",
    "CanonicalConfigurationConversionReviewV3",
    "CanonicalConfigurationLifecycleV3",
    "CanonicalConfigurationRevisionV3",
    "CanonicalConfigurationValidationV3",
    "CanonicalFieldMetadataV3",
    "CanonicalReferenceBindingV3",
    "CanonicalReferenceHealthV3",
    "CanonicalV2ToV3MigrationError",
    "ConfigurationDefaultPolicyV3",
    "ConfigurationEditabilityV3",
    "ConfigurationOwnerV3",
    "ConfigurationScopesV3",
    "DiagnosticDebugPolicyV3",
    "DiagnosticsConfigurationV3",
    "HeatingConfigurationV3",
    "HeatingGlobalConfigurationV3",
    "GREENFIELD_HEAT_SOURCE_ID_V3",
    "GREENFIELD_PRIMARY_SENSOR_ID_V3",
    "GREENFIELD_ZONE_ID_V3",
    "GreenfieldHeatingBindingsV3",
    "HeatSourceCommandStrategyV3",
    "HeatSourceConfigurationV3",
    "HeatSourceObservationBindingsV3",
    "HeatSourceProtectionPolicyV3",
    "NotificationRecipientConfigurationV3",
    "NotificationsConfigurationV3",
    "PrimaryTemperatureSensorV3",
    "ProviderServiceCallV3",
    "ZoneConfigurationV3",
    "ZoneDemandPolicyV3",
    "ZoneHeatDeliveryConfigurationV3",
    "ZoneTopologyV3",
    "canonical_field_registry_v3",
    "canonical_reference_bindings_v3",
    "author_greenfield_heating_scopes_v3",
    "conversion_configuration_id_v3",
    "migrate_heating_v2_revision_to_v3",
    "new_configuration_id_v3",
]
