"""Application configuration resolution."""

from controlel.application.configuration.canonical_v3 import (
    CANONICAL_CONFIGURATION_SCHEMA_VERSION_V3,
    CanonicalConfigurationRevisionV3,
    CanonicalFieldMetadataV3,
    ConfigurationDefaultPolicyV3,
    ConfigurationEditabilityV3,
    ConfigurationOwnerV3,
    DiagnosticDebugPolicyV3,
    DiagnosticsConfigurationV3,
    HeatingConfigurationV3,
    HeatingGlobalConfigurationV3,
    HeatSourceCommandStrategyV3,
    HeatSourceConfigurationV3,
    HeatSourceObservationBindingsV3,
    HeatSourceProtectionPolicyV3,
    NotificationRecipientConfigurationV3,
    NotificationsConfigurationV3,
    PrimaryTemperatureSensorV3,
    ProviderServiceCallV3,
    ZoneConfigurationV3,
    ZoneDemandPolicyV3,
    ZoneHeatDeliveryConfigurationV3,
    ZoneTopologyV3,
    canonical_field_registry_v3,
)
from controlel.application.configuration.canonical_v3_migration import (
    CanonicalV2ToV3MigrationError,
    migrate_heating_v2_revision_to_v3,
)

__all__ = [
    "CANONICAL_CONFIGURATION_SCHEMA_VERSION_V3",
    "CanonicalConfigurationRevisionV3",
    "CanonicalFieldMetadataV3",
    "CanonicalV2ToV3MigrationError",
    "ConfigurationDefaultPolicyV3",
    "ConfigurationEditabilityV3",
    "ConfigurationOwnerV3",
    "DiagnosticDebugPolicyV3",
    "DiagnosticsConfigurationV3",
    "HeatingConfigurationV3",
    "HeatingGlobalConfigurationV3",
    "HeatSourceCommandStrategyV3",
    "HeatSourceConfigurationV3",
    "HeatSourceObservationBindingsV3",
    "HeatSourceProtectionPolicyV3",
    "NotificationRecipientConfigurationV3",
    "NotificationsConfigurationV3",
    "PrimaryTemperatureSensorV3",
    "ProviderServiceCallV3",
    "ZoneConfigurationV3",
    "ZoneDemandPolicyV3",
    "ZoneHeatDeliveryConfigurationV3",
    "ZoneTopologyV3",
    "canonical_field_registry_v3",
    "migrate_heating_v2_revision_to_v3",
]
