"""Authoritative defaults for newly-created canonical configuration.

These values are recommendations for new configuration only. Migration code
must copy historical values explicitly and must never use these constants as
fallbacks for a legacy document.
"""

from typing import Literal

NEW_CONFIGURATION_TARGET_TEMPERATURE_CELSIUS = 21.0
NEW_CONFIGURATION_HEATING_TURN_ON_DIFFERENTIAL_CELSIUS = 0.3
NEW_CONFIGURATION_HEATING_TURN_OFF_DIFFERENTIAL_CELSIUS = 0.1
NEW_CONFIGURATION_HEAT_DEMAND_CONFIRMATION_SECONDS = 120.0
NEW_CONFIGURATION_PRIMARY_MEASUREMENT_MAX_AGE_SECONDS = 900.0
NEW_CONFIGURATION_MAXIMUM_FUTURE_SKEW_SECONDS = 30.0
NEW_CONFIGURATION_INDETERMINATE_GRACE_PERIOD_SECONDS = 120.0
NEW_CONFIGURATION_MINIMUM_HEATING_ON_SECONDS = 600.0
NEW_CONFIGURATION_MINIMUM_HEATING_OFF_SECONDS = 300.0

NEW_CONFIGURATION_HEAT_DELIVERY_ASSIST_POLICY: Literal["no_assist", "always_assist_while_heating"] = "no_assist"
NEW_CONFIGURATION_HEAT_DELIVERY_ASSIST_TARGET_CELSIUS = 30.0

NEW_CONFIGURATION_DIAGNOSTIC_STEADY_PROFILE: Literal["basic", "detailed"] = "basic"
NEW_CONFIGURATION_DEBUG_DURATION_SECONDS = 3600.0
NEW_CONFIGURATION_DEBUG_UNTIL_CHANGED = False
